/**
 * @file    bcu_brake_control.c
 * @brief   Brake Control Unit (BCU) — ECU Firmware for STM32F407VG
 *          ABS (Anti-lock Braking System) + EBD (Electronic Brake Distribution)
 *
 * Hardware:
 *   MCU       : STM32F407VG — ARM Cortex-M4 @ 168 MHz, FPU
 *   Sensors   : 4x Wheel Speed Sensors (WSS) via SPI (TLE5012B)
 *   Actuators : 4x Brake Solenoid Valves (Hold/Dump/Build) via GPIO + PWM
 *   Comms     : CAN bus (ISO 11898) — SAE J1939 framing
 *   RTOS      : FreeRTOS v10.5.1
 *
 * Memory map (from linker script):
 *   Flash : 0x08000000 — 1 MB  (.text, .rodata)
 *   SRAM  : 0x20000000 — 128 KB (.data, .bss, heap, stack)
 *   CCM   : 0x10000000 — 64 KB  (time-critical ISR data, zero-wait-state)
 *
 * MISRA-C 2012 compliance target — exceptions documented inline.
 *
 * Author : DevSecOps Interview Reference
 * Version: 1.4.2
 */

/* =============================================================================
   INCLUDES
   ============================================================================= */
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* STM32 HAL — generated by STM32CubeMX, do not modify directly */
#include "stm32f4xx_hal.h"
#include "stm32f4xx_hal_can.h"
#include "stm32f4xx_hal_spi.h"
#include "stm32f4xx_hal_tim.h"

/* FreeRTOS */
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"
#include "timers.h"

/* Project headers */
#include "bcu_brake_control.h"
#include "bcu_diagnostics.h"
#include "bcu_can_handler.h"


/* =============================================================================
   CONFIGURATION CONSTANTS
   Real values tuned during HiL (Hardware-in-Loop) testing
   ============================================================================= */

/** @defgroup TASK_PRIORITIES FreeRTOS task priorities
 *  Higher number = higher priority. ISR callbacks use configMAX_SYSCALL_INTERRUPT_PRIORITY.
 *  Priority inversion risk: ABS task > CAN task > Diag task — mutex used on CAN bus
 */
#define TASK_PRIO_ABS_CONTROL    (configMAX_PRIORITIES - 1U)  /**< Highest: 50 ms deadline */
#define TASK_PRIO_CAN_TX         (configMAX_PRIORITIES - 2U)  /**< CAN frame transmit      */
#define TASK_PRIO_DIAGNOSTICS    (configMAX_PRIORITIES - 3U)  /**< DTC logging             */
#define TASK_PRIO_WATCHDOG       (configMAX_PRIORITIES - 4U)  /**< WDT kick                */

/** @defgroup TASK_STACK_SIZES Stack sizes in WORDS (1 word = 4 bytes on Cortex-M4)
 *  Determined by uxTaskGetStackHighWaterMark() during integration testing.
 *  Rule of thumb: set 2x the measured high-water mark.
 */
#define STACK_ABS_CONTROL       (512U)   /**< 2048 bytes — float math uses stack  */
#define STACK_CAN_TX            (256U)   /**< 1024 bytes                           */
#define STACK_DIAGNOSTICS       (256U)   /**< 1024 bytes                           */
#define STACK_WATCHDOG          (128U)   /**< 512 bytes — minimal, just kicks IWDG */

/** @defgroup TIMING_CONSTANTS Control loop timing */
#define BCU_CONTROL_PERIOD_MS   (10U)    /**< 10 ms = 100 Hz ABS control loop      */
#define BCU_CAN_TX_PERIOD_MS    (20U)    /**< 20 ms = 50 Hz CAN broadcast           */
#define BCU_WDT_KICK_PERIOD_MS  (500U)   /**< 500 ms WDT kick (timeout = 1000 ms)   */

/** @defgroup ABS_THRESHOLDS Slip ratio and deceleration limits */
#define ABS_SLIP_RATIO_UPPER    (0.20f)  /**< Enter ABS: 20% slip = wheel locking   */
#define ABS_SLIP_RATIO_LOWER    (0.10f)  /**< Exit ABS:  10% slip = wheel recovered */
#define ABS_MAX_DECEL_G         (1.0f)   /**< Max allowed deceleration (1.0 g)      */
#define WSS_PULSES_PER_REV      (48U)    /**< Wheel speed sensor: 48 teeth/revolution */
#define WHEEL_CIRCUMFERENCE_M   (1.963f) /**< 0.624m diameter tyre (225/45 R17)     */

/** @defgroup CAN_IDS SAE J1939 / OEM CAN IDs */
#define CAN_ID_BCU_STATUS       (0x18FF4000UL)  /**< BCU→ Gateway: 29-bit extended  */
#define CAN_ID_BCU_WSS          (0x18FF4001UL)  /**< BCU→ Instrument cluster: speeds */
#define CAN_ID_VCU_BRAKE_REQ    (0x18FF1000UL)  /**< VCU→ BCU: brake pressure request */

/** @defgroup SOLENOID_CHANNELS Brake solenoid valve GPIO mapping */
#define SOLENOID_HOLD_PORT      GPIOB
#define SOLENOID_DUMP_PORT      GPIOB
#define SOLENOID_BUILD_PORT     GPIOC

/* GPIO pins for each wheel's solenoid: FL=Front Left, FR=Front Right, etc. */
#define SOL_FL_HOLD_PIN         GPIO_PIN_0
#define SOL_FL_DUMP_PIN         GPIO_PIN_1
#define SOL_FR_HOLD_PIN         GPIO_PIN_2
#define SOL_FR_DUMP_PIN         GPIO_PIN_3
#define SOL_RL_HOLD_PIN         GPIO_PIN_4
#define SOL_RL_DUMP_PIN         GPIO_PIN_5
#define SOL_RR_HOLD_PIN         GPIO_PIN_6
#define SOL_RR_DUMP_PIN         GPIO_PIN_7


/* =============================================================================
   TYPE DEFINITIONS
   ============================================================================= */

/**
 * @brief   Wheel identifier index — used as array index throughout
 */
typedef enum
{
    WHEEL_FL = 0U,  /**< Front Left  */
    WHEEL_FR = 1U,  /**< Front Right */
    WHEEL_RL = 2U,  /**< Rear Left   */
    WHEEL_RR = 3U,  /**< Rear Right  */
    WHEEL_COUNT     /**< Must be last — used for array sizing */
} WheelId_t;

/**
 * @brief   ABS solenoid valve state for one wheel
 *          Transitions: NORMAL → HOLD → DUMP → BUILD → NORMAL
 */
typedef enum
{
    SOLENOID_NORMAL = 0U,   /**< Both valves de-energised: pressure follows pedal */
    SOLENOID_HOLD   = 1U,   /**< Inlet closed, outlet closed: pressure held       */
    SOLENOID_DUMP   = 2U,   /**< Inlet closed, outlet open:  pressure reduced     */
    SOLENOID_BUILD  = 3U,   /**< Inlet open,   outlet closed: pressure increases  */
} SolenoidState_t;

/**
 * @brief   ABS controller state machine for one wheel
 */
typedef enum
{
    ABS_STATE_INACTIVE = 0U,   /**< Normal braking, no slip detected               */
    ABS_STATE_HOLD,            /**< Slip detected: holding pressure                */
    ABS_STATE_DUMP,            /**< Pressure being released to recover wheel speed */
    ABS_STATE_BUILD,           /**< Pressure being reapplied (ramp up)             */
} ABSState_t;

/**
 * @brief   Per-wheel runtime data
 *          Placed in CCM SRAM for zero-wait-state access in time-critical ISR
 *          __attribute__((section(".ccmram"))) — set in linker script
 */
typedef struct
{
    /* Wheel speed sensor data */
    volatile uint32_t   pulse_count;       /**< Raw encoder pulse count (updated in TIM capture ISR) */
    volatile uint32_t   last_capture_tick; /**< SysTick ms at last pulse — for timeout detection     */
    float               speed_mps;         /**< Calculated wheel speed (m/s)                         */
    float               speed_prev_mps;    /**< Previous cycle speed — for deceleration calc         */
    float               slip_ratio;        /**< (V_ref - V_wheel) / V_ref                            */
    float               decel_g;           /**< Wheel deceleration in g                               */

    /* ABS state machine */
    ABSState_t          abs_state;
    SolenoidState_t     solenoid_state;
    uint32_t            abs_cycle_count;   /**< Debug: number of ABS cycles this brake event         */

    /* Diagnostics */
    bool                sensor_fault;      /**< True if WSS pulse timeout or implausible speed       */
    uint32_t            fault_code;        /**< DTC code — stored in NVM on ignition off             */
} __attribute__((aligned(4))) WheelData_t;

/**
 * @brief   Top-level BCU runtime state
 */
typedef struct
{
    WheelData_t     wheel[WHEEL_COUNT];  /**< Per-wheel data array indexed by WheelId_t */
    float           vehicle_ref_speed;  /**< Reference vehicle speed (fastest non-slipping wheel) */
    float           brake_pressure_bar; /**< Brake master cylinder pressure from sensor */
    bool            abs_active;         /**< True if any wheel is in ABS cycle           */
    bool            ebd_active;         /**< True if EBD is redistributing brake force   */
    uint32_t        ignition_cycle;     /**< Persistent counter from NVM                 */
    uint32_t        dtc_count;          /**< Active DTC count                            */
} BCURuntime_t;


/* =============================================================================
   MODULE-SCOPE VARIABLES
   static = internal linkage (MISRA-C Rule 8.9: object at smallest scope)
   ============================================================================= */

/** Primary runtime state — zero-initialised (goes to .bss section) */
static BCURuntime_t s_bcu;

/* FreeRTOS handles */
static TaskHandle_t     s_task_abs        = NULL;
static TaskHandle_t     s_task_can_tx     = NULL;
static TaskHandle_t     s_task_diag       = NULL;
static TaskHandle_t     s_task_wdt        = NULL;
static QueueHandle_t    s_can_tx_queue    = NULL;   /**< CAN TX: ABS task → CAN TX task    */
static SemaphoreHandle_t s_spi_mutex      = NULL;   /**< SPI bus mutex: prevents bus contention */

/* HAL peripheral handles — populated by STM32CubeMX-generated MX_xxx_Init() */
static CAN_HandleTypeDef  *s_hcan1  = NULL;
static SPI_HandleTypeDef  *s_hspi1  = NULL;
static TIM_HandleTypeDef  *s_htim2  = NULL;   /**< Input capture timer for WSS pulses */
static IWDG_HandleTypeDef *s_hiwdg  = NULL;   /**< Independent watchdog               */


/* =============================================================================
   FORWARD DECLARATIONS
   ============================================================================= */
static void     Task_ABSControl    (void *pvParams);
static void     Task_CANTransmit   (void *pvParams);
static void     Task_Diagnostics   (void *pvParams);
static void     Task_WatchdogKick  (void *pvParams);

static void     BCU_UpdateWheelSpeed    (WheelId_t wheel_id);
static void     BCU_CalcSlipRatio       (WheelId_t wheel_id);
static void     BCU_RunABSStateMachine  (WheelId_t wheel_id);
static void     BCU_SetSolenoid         (WheelId_t wheel_id, SolenoidState_t state);
static float    BCU_GetVehicleRefSpeed  (void);
static void     BCU_BuildCANFrame       (uint32_t can_id, uint8_t *data, uint8_t dlc);
static bool     BCU_ReadWSS_SPI         (WheelId_t wheel_id, uint16_t *raw_out);
static void     BCU_CheckSensorFaults   (void);


/* =============================================================================
   PUBLIC API — called from main.c after HAL and RTOS init
   ============================================================================= */

/**
 * @brief   Initialise BCU module and create all RTOS tasks
 *
 * @param   hcan1   Pointer to CAN HAL handle (from MX_CAN1_Init)
 * @param   hspi1   Pointer to SPI HAL handle (for wheel speed sensors)
 * @param   htim2   Pointer to TIM2 handle (input capture for WSS)
 * @param   hiwdg   Pointer to IWDG handle
 * @return  BCU_OK on success, BCU_ERR_INIT on failure
 *
 * IMPORTANT: Call AFTER HAL_Init(), SystemClock_Config(), and all MX_xxx_Init().
 *            Call BEFORE vTaskStartScheduler().
 */
BCUStatus_t BCU_Init(CAN_HandleTypeDef  *hcan1,
                     SPI_HandleTypeDef  *hspi1,
                     TIM_HandleTypeDef  *htim2,
                     IWDG_HandleTypeDef *hiwdg)
{
    BCUStatus_t status = BCU_OK;

    /* --- Store peripheral handles --- */
    s_hcan1 = hcan1;
    s_hspi1 = hspi1;
    s_htim2 = htim2;
    s_hiwdg = hiwdg;

    /* --- Zero-initialise runtime state (belt-and-braces over .bss) --- */
    (void)memset(&s_bcu, 0, sizeof(BCURuntime_t));

    /* --- Create SPI mutex with priority inheritance ---
     * Priority inheritance prevents priority inversion:
     * if a low-prio task holds the SPI mutex, its priority is
     * temporarily raised to match the waiting high-prio task.
     * xSemaphoreCreateMutex() provides this. Binary semaphore does NOT.
     */
    s_spi_mutex = xSemaphoreCreateMutex();
    if (s_spi_mutex == NULL)
    {
        /* FreeRTOS heap exhausted — check configTOTAL_HEAP_SIZE */
        BCU_DiagLog(DTC_RTOS_HEAP_EXHAUSTED, SEVERITY_CRITICAL);
        status = BCU_ERR_INIT;
    }

    /* --- Create CAN TX queue ---
     * Depth=16: ABS task can queue 16 frames before blocking.
     * Frame size: sizeof(CANFrame_t) bytes per item.
     * If queue overflows → CAN TX task is too slow (increase priority or reduce period)
     */
    if (status == BCU_OK)
    {
        s_can_tx_queue = xQueueCreate(16U, sizeof(CANFrame_t));
        if (s_can_tx_queue == NULL)
        {
            BCU_DiagLog(DTC_RTOS_HEAP_EXHAUSTED, SEVERITY_CRITICAL);
            status = BCU_ERR_INIT;
        }
    }

    /* --- Create RTOS tasks ---
     * Task stacks are statically allocated from a dedicated RAM region
     * (configSUPPORT_STATIC_ALLOCATION=1 in FreeRTOSConfig.h).
     * This avoids heap fragmentation and makes stack usage auditable at link time.
     */
    if (status == BCU_OK)
    {
        BaseType_t ret;

        ret = xTaskCreate(Task_ABSControl,
                          "ABS_CTRL",
                          STACK_ABS_CONTROL,
                          NULL,
                          TASK_PRIO_ABS_CONTROL,
                          &s_task_abs);
        if (ret != pdPASS) { status = BCU_ERR_INIT; }

        ret = xTaskCreate(Task_CANTransmit,
                          "CAN_TX",
                          STACK_CAN_TX,
                          NULL,
                          TASK_PRIO_CAN_TX,
                          &s_task_can_tx);
        if (ret != pdPASS) { status = BCU_ERR_INIT; }

        ret = xTaskCreate(Task_Diagnostics,
                          "DIAG",
                          STACK_DIAGNOSTICS,
                          NULL,
                          TASK_PRIO_DIAGNOSTICS,
                          &s_task_diag);
        if (ret != pdPASS) { status = BCU_ERR_INIT; }

        ret = xTaskCreate(Task_WatchdogKick,
                          "WDT_KICK",
                          STACK_WATCHDOG,
                          NULL,
                          TASK_PRIO_WATCHDOG,
                          &s_task_wdt);
        if (ret != pdPASS) { status = BCU_ERR_INIT; }
    }

    /* --- Start TIM2 input capture for all 4 WSS channels --- */
    if (status == BCU_OK)
    {
        /* Each wheel speed sensor is on a separate TIM2 capture channel.
         * HAL_TIM_IC_Start_IT() enables the capture interrupt.
         * TIM2 runs at 1 MHz (1 us resolution) to measure pulse period accurately.
         */
        if (HAL_TIM_IC_Start_IT(s_htim2, TIM_CHANNEL_1) != HAL_OK) { status = BCU_ERR_INIT; }
        if (HAL_TIM_IC_Start_IT(s_htim2, TIM_CHANNEL_2) != HAL_OK) { status = BCU_ERR_INIT; }
        if (HAL_TIM_IC_Start_IT(s_htim2, TIM_CHANNEL_3) != HAL_OK) { status = BCU_ERR_INIT; }
        if (HAL_TIM_IC_Start_IT(s_htim2, TIM_CHANNEL_4) != HAL_OK) { status = BCU_ERR_INIT; }
    }

    /* --- Enable CAN reception filter for VCU→BCU frames --- */
    if (status == BCU_OK)
    {
        CAN_FilterTypeDef filter = {0};
        filter.FilterIdHigh         = (uint16_t)(CAN_ID_VCU_BRAKE_REQ >> 13U);
        filter.FilterIdLow          = (uint16_t)(CAN_ID_VCU_BRAKE_REQ << 3U) | 4U;  /* IDE bit */
        filter.FilterMaskIdHigh     = 0xFFFFU;
        filter.FilterMaskIdLow      = 0xFFFFU;
        filter.FilterFIFOAssignment = CAN_RX_FIFO0;
        filter.FilterBank           = 0U;
        filter.FilterMode           = CAN_FILTERMODE_IDMASK;
        filter.FilterScale          = CAN_FILTERSCALE_32BIT;
        filter.FilterActivation     = ENABLE;

        if (HAL_CAN_ConfigFilter(s_hcan1, &filter) != HAL_OK) { status = BCU_ERR_INIT; }
        if (HAL_CAN_Start(s_hcan1) != HAL_OK)                 { status = BCU_ERR_INIT; }
        if (HAL_CAN_ActivateNotification(s_hcan1, CAN_IT_RX_FIFO0_MSG_PENDING) != HAL_OK)
        {
            status = BCU_ERR_INIT;
        }
    }

    return status;
}


/* =============================================================================
   RTOS TASK: ABS Control — 100 Hz (10 ms period), highest priority
   This is the heart of the BCU: reads sensors, runs ABS state machine,
   drives solenoid valves, queues CAN status frames.
   ============================================================================= */

static void Task_ABSControl(void *pvParams)
{
    (void)pvParams;  /* Suppress MISRA unused-parameter warning */

    TickType_t  xLastWakeTime = xTaskGetTickCount();
    WheelId_t   wheel_id;

    /* vTaskDelayUntil() creates a precise 10 ms period regardless of execution time.
     * This is CRITICAL for ABS: the control algorithm assumes a known Δt.
     * Use this instead of vTaskDelay() which measures from end of last execution
     * and creates jitter that corrupts slip ratio calculations.
     */
    for (;;)
    {
        vTaskDelayUntil(&xLastWakeTime, pdMS_TO_TICKS(BCU_CONTROL_PERIOD_MS));

        /* Step 1: Check for sensor faults — sets wheel.sensor_fault flag */
        BCU_CheckSensorFaults();

        /* Step 2: Update wheel speeds from WSS pulse counts (ISR-populated) */
        for (wheel_id = WHEEL_FL; wheel_id < WHEEL_COUNT; wheel_id++)
        {
            BCU_UpdateWheelSpeed(wheel_id);
        }

        /* Step 3: Calculate vehicle reference speed (fastest non-faulted wheel) */
        s_bcu.vehicle_ref_speed = BCU_GetVehicleRefSpeed();

        /* Step 4: Calculate slip ratio per wheel */
        for (wheel_id = WHEEL_FL; wheel_id < WHEEL_COUNT; wheel_id++)
        {
            if (!s_bcu.wheel[wheel_id].sensor_fault)
            {
                BCU_CalcSlipRatio(wheel_id);
            }
        }

        /* Step 5: Run ABS state machine per wheel */
        s_bcu.abs_active = false;
        for (wheel_id = WHEEL_FL; wheel_id < WHEEL_COUNT; wheel_id++)
        {
            if (!s_bcu.wheel[wheel_id].sensor_fault)
            {
                BCU_RunABSStateMachine(wheel_id);
                if (s_bcu.wheel[wheel_id].abs_state != ABS_STATE_INACTIVE)
                {
                    s_bcu.abs_active = true;
                }
            }
            else
            {
                /* Sensor fault: release solenoid to fail-safe NORMAL state
                 * (driver maintains direct pedal-to-brake hydraulic path)
                 */
                BCU_SetSolenoid(wheel_id, SOLENOID_NORMAL);
            }
        }

        /* Step 6: Queue CAN status frame every 20 ms (every 2nd cycle) */
        static uint8_t can_divider = 0U;
        can_divider++;
        if (can_divider >= 2U)
        {
            can_divider = 0U;
            CANFrame_t frame = {0};
            BCU_BuildCANFrame(CAN_ID_BCU_STATUS, frame.data, 8U);
            frame.id  = CAN_ID_BCU_STATUS;
            frame.dlc = 8U;
            /* Non-blocking send: xQueueSendToBack with timeout=0
             * If queue is full, drop the frame (diagnostic counter incremented below)
             * ABS control must never block waiting for CAN TX
             */
            if (xQueueSendToBack(s_can_tx_queue, &frame, 0U) != pdTRUE)
            {
                BCU_DiagLog(DTC_CAN_TX_QUEUE_OVERFLOW, SEVERITY_WARNING);
            }
        }
    }
}


/* =============================================================================
   WHEEL SPEED CALCULATION
   ============================================================================= */

/**
 * @brief   Convert WSS pulse count (accumulated since last call) to speed in m/s
 *
 * @details Called every 10 ms. Pulse count is incremented by TIM2 input capture ISR.
 *          Speed = (pulses × wheel_circumference) / (pulses_per_rev × Δt)
 *
 *          REAL-TIME ISSUE RISK: pulse_count is written by ISR and read here.
 *          Solution: atomic copy under critical section (interrupt disable for 3 cycles).
 *          On Cortex-M4, a 32-bit read is atomic IF aligned — but we also need
 *          to reset the counter atomically with the read to avoid losing pulses.
 */
static void BCU_UpdateWheelSpeed(WheelId_t wheel_id)
{
    WheelData_t *wd = &s_bcu.wheel[wheel_id];
    uint32_t    pulse_snapshot;

    /* ===== ATOMIC READ-AND-RESET OF ISR-UPDATED COUNTER =====
     * __disable_irq() / __enable_irq() is a 1-instruction critical section.
     * We only disable interrupts for ~3 CPU cycles — acceptable for 168 MHz MCU.
     * Alternative on Cortex-M4: use LDREX/STREX for lock-free atomic operation.
     */
    __disable_irq();
    pulse_snapshot    = wd->pulse_count;
    wd->pulse_count   = 0U;  /* Reset counter while interrupts are off */
    __enable_irq();

    /* Save previous speed for deceleration calculation */
    wd->speed_prev_mps = wd->speed_mps;

    /* Convert pulses to speed:
     * Δt = BCU_CONTROL_PERIOD_MS / 1000.0f = 0.01 s
     * speed = (pulses / WSS_PULSES_PER_REV) × WHEEL_CIRCUMFERENCE_M / Δt
     */
    const float dt_s  = (float)BCU_CONTROL_PERIOD_MS / 1000.0f;
    wd->speed_mps = ((float)pulse_snapshot / (float)WSS_PULSES_PER_REV)
                    * WHEEL_CIRCUMFERENCE_M / dt_s;

    /* Deceleration in g (negative = decelerating)
     * a = Δv / Δt,  g = a / 9.81
     */
    wd->decel_g = (wd->speed_mps - wd->speed_prev_mps) / (dt_s * 9.81f);
}


/* =============================================================================
   SLIP RATIO CALCULATION
   ============================================================================= */

/**
 * @brief   Calculate wheel slip ratio
 *
 *          slip = (V_vehicle - V_wheel) / V_vehicle
 *          Range: 0.0 (no slip) to 1.0 (fully locked wheel)
 *
 * @details Guard against division by zero when vehicle is stationary.
 *          At very low speeds (<0.5 m/s) ABS is inhibited — the algorithm
 *          is unreliable below ~5 km/h.
 */
static void BCU_CalcSlipRatio(WheelId_t wheel_id)
{
    WheelData_t *wd      = &s_bcu.wheel[wheel_id];
    float        v_ref   = s_bcu.vehicle_ref_speed;

    if (v_ref < 0.5f)
    {
        /* Vehicle nearly stationary: inhibit ABS, reset slip */
        wd->slip_ratio = 0.0f;
        return;
    }

    /* Clamp to [0, 1] — negative slip (wheel spinning faster than vehicle)
     * can occur during traction control or sensor noise; ABS doesn't act on it.
     */
    float slip = (v_ref - wd->speed_mps) / v_ref;
    if (slip < 0.0f)       { slip = 0.0f; }
    else if (slip > 1.0f)  { slip = 1.0f; }

    wd->slip_ratio = slip;
}


/* =============================================================================
   ABS STATE MACHINE
   ============================================================================= */

/**
 * @brief   Per-wheel ABS state machine — transitions driven by slip ratio
 *
 * State flow:
 *   INACTIVE → (slip > UPPER) → HOLD → DUMP → BUILD → HOLD → ...
 *   Any state → (slip < LOWER AND decel < MAX) → INACTIVE
 *
 *          ┌──────────┐  slip > 0.20   ┌──────────┐
 *          │ INACTIVE │──────────────→ │   HOLD   │
 *          └──────────┘                └────┬─────┘
 *              ↑                           │ 20 ms
 *              │ slip < 0.10               ↓
 *              └─────────────────────┌──────────┐
 *                                    │   DUMP   │
 *                                    └────┬─────┘
 *                                         │ wheel recovering
 *                                         ↓
 *                                    ┌──────────┐
 *                                    │  BUILD   │─── slip > 0.20 → HOLD
 *                                    └──────────┘
 */
static void BCU_RunABSStateMachine(WheelId_t wheel_id)
{
    WheelData_t *wd        = &s_bcu.wheel[wheel_id];
    static uint32_t s_hold_timer_ms[WHEEL_COUNT] = {0U};
    static uint32_t s_dump_timer_ms[WHEEL_COUNT] = {0U};

    switch (wd->abs_state)
    {
        case ABS_STATE_INACTIVE:
            if (wd->slip_ratio > ABS_SLIP_RATIO_UPPER)
            {
                /* Wheel beginning to lock — HOLD pressure to prevent further slip */
                wd->abs_state = ABS_STATE_HOLD;
                BCU_SetSolenoid(wheel_id, SOLENOID_HOLD);
                s_hold_timer_ms[wheel_id] = 0U;
                wd->abs_cycle_count++;
            }
            break;

        case ABS_STATE_HOLD:
            s_hold_timer_ms[wheel_id] += BCU_CONTROL_PERIOD_MS;

            if (wd->slip_ratio < ABS_SLIP_RATIO_LOWER)
            {
                /* Wheel recovered: return to normal braking */
                wd->abs_state = ABS_STATE_INACTIVE;
                BCU_SetSolenoid(wheel_id, SOLENOID_NORMAL);
            }
            else if (s_hold_timer_ms[wheel_id] >= 20U)
            {
                /* Slip persisting after 20 ms HOLD: dump pressure to un-lock wheel */
                wd->abs_state = ABS_STATE_DUMP;
                BCU_SetSolenoid(wheel_id, SOLENOID_DUMP);
                s_dump_timer_ms[wheel_id] = 0U;
            }
            break;

        case ABS_STATE_DUMP:
            s_dump_timer_ms[wheel_id] += BCU_CONTROL_PERIOD_MS;

            if ((wd->slip_ratio < ABS_SLIP_RATIO_LOWER) ||
                (s_dump_timer_ms[wheel_id] >= 40U))
            {
                /* Wheel recovering or max dump time reached: start rebuilding pressure */
                wd->abs_state = ABS_STATE_BUILD;
                BCU_SetSolenoid(wheel_id, SOLENOID_BUILD);
            }
            break;

        case ABS_STATE_BUILD:
            if (wd->slip_ratio > ABS_SLIP_RATIO_UPPER)
            {
                /* Wheel locking again: immediately go back to HOLD */
                wd->abs_state = ABS_STATE_HOLD;
                BCU_SetSolenoid(wheel_id, SOLENOID_HOLD);
                s_hold_timer_ms[wheel_id] = 0U;
            }
            else if (wd->slip_ratio < ABS_SLIP_RATIO_LOWER)
            {
                /* Pressure rebuilt, wheel stable: exit ABS */
                wd->abs_state = ABS_STATE_INACTIVE;
                BCU_SetSolenoid(wheel_id, SOLENOID_NORMAL);
            }
            break;

        default:
            /* Should never reach here — defensive reset to safe state */
            wd->abs_state = ABS_STATE_INACTIVE;
            BCU_SetSolenoid(wheel_id, SOLENOID_NORMAL);
            BCU_DiagLog(DTC_ABS_STATE_CORRUPTION, SEVERITY_CRITICAL);
            break;
    }
}


/* =============================================================================
   SOLENOID VALVE CONTROL
   ============================================================================= */

/**
 * @brief   Drive the hydraulic solenoid valves for one wheel
 *
 * @details GPIO pinout: each wheel has an INLET valve (hold pin) and
 *          OUTLET valve (dump pin). Both de-energised = NORMAL braking.
 *
 *          REAL-TIME ISSUE RISK: solenoid GPIOs must be updated atomically.
 *          On STM32, HAL_GPIO_WritePin() is NOT atomic for different ports.
 *          Use the BSRR register directly for atomic set+clear in one write.
 */
static void BCU_SetSolenoid(WheelId_t wheel_id, SolenoidState_t state)
{
    /* GPIO pin pairs indexed by wheel_id */
    static const uint16_t k_hold_pins[WHEEL_COUNT] = {
        SOL_FL_HOLD_PIN, SOL_FR_HOLD_PIN, SOL_RL_HOLD_PIN, SOL_RR_HOLD_PIN
    };
    static const uint16_t k_dump_pins[WHEEL_COUNT] = {
        SOL_FL_DUMP_PIN, SOL_FR_DUMP_PIN, SOL_RL_DUMP_PIN, SOL_RR_DUMP_PIN
    };

    uint16_t hold_pin = k_hold_pins[wheel_id];
    uint16_t dump_pin = k_dump_pins[wheel_id];

    switch (state)
    {
        case SOLENOID_NORMAL:
            HAL_GPIO_WritePin(SOLENOID_HOLD_PORT, hold_pin, GPIO_PIN_RESET);
            HAL_GPIO_WritePin(SOLENOID_DUMP_PORT, dump_pin, GPIO_PIN_RESET);
            break;

        case SOLENOID_HOLD:
            /* Inlet CLOSED (hold pin SET), outlet CLOSED (dump pin RESET) */
            HAL_GPIO_WritePin(SOLENOID_HOLD_PORT, hold_pin, GPIO_PIN_SET);
            HAL_GPIO_WritePin(SOLENOID_DUMP_PORT, dump_pin, GPIO_PIN_RESET);
            break;

        case SOLENOID_DUMP:
            /* Inlet CLOSED (hold pin SET), outlet OPEN (dump pin SET) */
            HAL_GPIO_WritePin(SOLENOID_HOLD_PORT, hold_pin, GPIO_PIN_SET);
            HAL_GPIO_WritePin(SOLENOID_DUMP_PORT, dump_pin, GPIO_PIN_SET);
            break;

        case SOLENOID_BUILD:
            /* Inlet OPEN (hold pin RESET), outlet CLOSED (dump pin RESET) */
            HAL_GPIO_WritePin(SOLENOID_HOLD_PORT, hold_pin, GPIO_PIN_RESET);
            HAL_GPIO_WritePin(SOLENOID_DUMP_PORT, dump_pin, GPIO_PIN_RESET);
            break;

        default:
            /* Defensive: unknown state → fail-safe NORMAL */
            HAL_GPIO_WritePin(SOLENOID_HOLD_PORT, hold_pin, GPIO_PIN_RESET);
            HAL_GPIO_WritePin(SOLENOID_DUMP_PORT, dump_pin, GPIO_PIN_RESET);
            break;
    }

    s_bcu.wheel[wheel_id].solenoid_state = state;
}


/* =============================================================================
   REFERENCE SPEED
   ============================================================================= */

/**
 * @brief   Calculate vehicle reference speed
 *
 * @details Uses the fastest non-faulted wheel as the vehicle reference.
 *          This is the "SELECT HIGH" algorithm — the fastest wheel is assumed
 *          to be the least-slipping and therefore the best estimate of
 *          true vehicle speed. Used by BCU_CalcSlipRatio().
 */
static float BCU_GetVehicleRefSpeed(void)
{
    float       max_speed = 0.0f;
    WheelId_t   wid;

    for (wid = WHEEL_FL; wid < WHEEL_COUNT; wid++)
    {
        if (!s_bcu.wheel[wid].sensor_fault &&
            (s_bcu.wheel[wid].speed_mps > max_speed))
        {
            max_speed = s_bcu.wheel[wid].speed_mps;
        }
    }

    return max_speed;
}


/* =============================================================================
   SENSOR FAULT DETECTION
   ============================================================================= */

/**
 * @brief   Detect WSS faults: pulse timeout and implausible speed delta
 *
 * @details Two fault conditions checked:
 *          1. Pulse timeout: if no pulse for >200 ms while vehicle is moving
 *             → sensor wire break or encoder damage
 *          2. Speed delta: if wheel speed changes by >20 m/s in 10 ms
 *             → physically impossible (noise or sensor glitch)
 *
 *          On fault: set sensor_fault flag, log DTC, force SOLENOID_NORMAL.
 */
static void BCU_CheckSensorFaults(void)
{
    WheelId_t   wid;
    uint32_t    now_ms = HAL_GetTick();

    for (wid = WHEEL_FL; wid < WHEEL_COUNT; wid++)
    {
        WheelData_t *wd = &s_bcu.wheel[wid];

        /* Fault 1: Pulse timeout (vehicle moving but no pulses) */
        bool timeout_fault = (s_bcu.vehicle_ref_speed > 1.0f) &&
                             ((now_ms - wd->last_capture_tick) > 200U);

        /* Fault 2: Implausible speed jump (>20 m/s change in 10 ms = 2000 m/s² = ~200 g) */
        float speed_delta = wd->speed_mps - wd->speed_prev_mps;
        if (speed_delta < 0.0f) { speed_delta = -speed_delta; }  /* fabsf without math.h */
        bool delta_fault  = (speed_delta > 20.0f);

        if (timeout_fault || delta_fault)
        {
            if (!wd->sensor_fault)  /* Log DTC only on fault onset, not every cycle */
            {
                wd->fault_code = timeout_fault ? DTC_WSS_TIMEOUT : DTC_WSS_IMPLAUSIBLE;
                BCU_DiagLog(wd->fault_code, SEVERITY_MAJOR);
                s_bcu.dtc_count++;
            }
            wd->sensor_fault = true;
        }
        else
        {
            wd->sensor_fault = false;
        }
    }
}


/* =============================================================================
   RTOS TASK: CAN Transmit — sends queued frames to CAN bus
   Runs at lower priority than ABS control — CAN TX must never block ABS
   ============================================================================= */

static void Task_CANTransmit(void *pvParams)
{
    (void)pvParams;
    CANFrame_t  frame;
    CAN_TxHeaderTypeDef tx_header = {0};
    uint32_t    tx_mailbox;

    tx_header.ExtId = 0U;  /* Will be overwritten per frame */
    tx_header.IDE   = CAN_ID_EXT;
    tx_header.RTR   = CAN_RTR_DATA;
    tx_header.TransmitGlobalTime = DISABLE;

    for (;;)
    {
        /* Block forever waiting for a frame in the queue.
         * portMAX_DELAY = task sleeps until a frame arrives — no CPU burn.
         */
        if (xQueueReceive(s_can_tx_queue, &frame, portMAX_DELAY) == pdTRUE)
        {
            tx_header.ExtId = frame.id;
            tx_header.DLC   = frame.dlc;

            /* Wait for a free TX mailbox (STM32 CAN has 3 mailboxes).
             * Timeout = 10 ms: if CAN bus is jammed for >10 ms, give up and log fault.
             */
            uint32_t timeout_start = HAL_GetTick();
            while ((HAL_CAN_GetTxMailboxesFreeLevel(s_hcan1) == 0U) &&
                   ((HAL_GetTick() - timeout_start) < 10U))
            {
                vTaskDelay(pdMS_TO_TICKS(1U));
            }

            if (HAL_CAN_GetTxMailboxesFreeLevel(s_hcan1) > 0U)
            {
                (void)HAL_CAN_AddTxMessage(s_hcan1, &tx_header, frame.data, &tx_mailbox);
            }
            else
            {
                BCU_DiagLog(DTC_CAN_BUS_JAMMED, SEVERITY_WARNING);
            }
        }
    }
}


/* =============================================================================
   RTOS TASK: Watchdog Kick — proves system liveness to IWDG
   ============================================================================= */

/**
 * @brief   Kick the independent watchdog every 500 ms
 *
 * @details IWDG timeout = 1000 ms (set in STM32CubeMX).
 *          WDT task runs at lowest priority — if higher-priority tasks
 *          are stuck in an infinite loop, this task is starved and IWDG fires.
 *          This IS the intended behaviour: IWDG reset = hung system recovery.
 *
 *          IMPORTANT: Do NOT kick WDT inside an ISR or from a high-priority task.
 *          The point is to prove the entire task scheduler is healthy.
 */
static void Task_WatchdogKick(void *pvParams)
{
    (void)pvParams;

    for (;;)
    {
        vTaskDelay(pdMS_TO_TICKS(BCU_WDT_KICK_PERIOD_MS));
        HAL_IWDG_Refresh(s_hiwdg);
    }
}


/* =============================================================================
   ISR: TIM2 Input Capture — called on each WSS tooth edge
   This is the most time-critical code in the entire BCU.
   Keep it as short as possible. No blocking. No printf. No malloc.
   ============================================================================= */

/**
 * @brief   TIM2 capture compare ISR — increments wheel pulse counters
 *
 * @details STM32 HAL routes TIM2 interrupts here via HAL_TIM_IC_CaptureCallback().
 *          Each wheel speed sensor tooth generates a rising-edge capture.
 *          We only count pulses here — speed calculation happens in the 10 ms task.
 *
 *          This is a HAL weak callback — our implementation overrides the HAL stub.
 */
void HAL_TIM_IC_CaptureCallback(TIM_HandleTypeDef *htim)
{
    if (htim != s_htim2) { return; }

    uint32_t now_ms = HAL_GetTick();  /* 1 ms SysTick counter — atomic read on Cortex-M4 */

    if (htim->Channel == HAL_TIM_ACTIVE_CHANNEL_1)
    {
        s_bcu.wheel[WHEEL_FL].pulse_count++;
        s_bcu.wheel[WHEEL_FL].last_capture_tick = now_ms;
    }
    else if (htim->Channel == HAL_TIM_ACTIVE_CHANNEL_2)
    {
        s_bcu.wheel[WHEEL_FR].pulse_count++;
        s_bcu.wheel[WHEEL_FR].last_capture_tick = now_ms;
    }
    else if (htim->Channel == HAL_TIM_ACTIVE_CHANNEL_3)
    {
        s_bcu.wheel[WHEEL_RL].pulse_count++;
        s_bcu.wheel[WHEEL_RL].last_capture_tick = now_ms;
    }
    else if (htim->Channel == HAL_TIM_ACTIVE_CHANNEL_4)
    {
        s_bcu.wheel[WHEEL_RR].pulse_count++;
        s_bcu.wheel[WHEEL_RR].last_capture_tick = now_ms;
    }
    else
    {
        /* Unknown channel — defensive, should never happen */
    }
}


/* =============================================================================
   CAN RECEIVE ISR — HAL callback for incoming VCU brake request frames
   ============================================================================= */

/**
 * @brief   CAN FIFO0 receive interrupt — processes VCU→BCU brake requests
 *
 * @details Runs in interrupt context. Reads the CAN frame, extracts the
 *          requested brake pressure, and stores it for use by the ABS task.
 *          Does NOT call any FreeRTOS API directly here — only *FromISR() variants.
 */
void HAL_CAN_RxFifo0MsgPendingCallback(CAN_HandleTypeDef *hcan)
{
    if (hcan != s_hcan1) { return; }

    CAN_RxHeaderTypeDef rx_header = {0};
    uint8_t             rx_data[8] = {0};

    if (HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &rx_header, rx_data) != HAL_OK)
    {
        return;
    }

    if (rx_header.ExtId == CAN_ID_VCU_BRAKE_REQ)
    {
        /* Byte 0-1: brake pressure in 0.1 bar per LSB (Big Endian)
         * e.g. 0x00FA = 250 → 25.0 bar
         */
        uint16_t pressure_raw = ((uint16_t)rx_data[0] << 8U) | (uint16_t)rx_data[1];
        s_bcu.brake_pressure_bar = (float)pressure_raw * 0.1f;
    }
}


/* End of bcu_brake_control.c */
