sonar.projectKey=bcu-brake-control
sonar.projectName=BCU Brake Control Unit

sonar.sources=src
sonar.tests=test

sonar.sourceEncoding=UTF-8

sonar.c.file.suffixes=.c,.h

sonar.cxx.cppcheck.reportPaths=cppcheck-report.xml

sonar.coverageReportPaths=coverage.xml
